### PR TITLE
update dashed-lines.glsl

### PR DESCRIPTION
**Pull request by parisa-hr**

### CODE REVIEW

**Review by 0smr — CHANGES_REQUESTED** [review]
Hi, and thank you for your PR; I had planned to make these modifications.
However, in order for this to merge, please remove any empty lines and modify the float number formats to minified (i.e. `1.0` to `1.`).

**Comment by parisa-hr** [comment]
> Hi, and thank you for your PR; I had planned to make these modifications. However, in order for this to merge, please remove any empty lines and modify the float number formats to minified (i.e. `1.0` to `1.`).

I did that but be friends with spaces :)
The spaces will be removed by the compiler and are only for the readability of the codes.

**Comment by 0smr** [comment]
@parisa-hr Thanks, but empty lines do not imply spaces, and this is the format I prefer.

**Comment by 0smr** [comment]
And the next time, please open an issue first.

**Pull request merged**
